extends Control
@onready var settings: Control = $Settings
@onready var v_box_container: VBoxContainer = $VBoxContainer
@onready var label: Label = $Label

func _ready() -> void:
	$VBoxContainer/StartGame.grab_focus()


func _on_start_game_pressed() -> void:
	get_tree().change_scene_to_file("res://scenes/game.tscn")


func _on_options_pressed() -> void:
	settings.visible = true
	v_box_container.visible = false
	label.visible = false

func _on_exit_pressed() -> void:
	get_tree().quit()

func _process(delta: float) -> void:
	if !settings.visible:
		v_box_container.visible = true
		label.visible = true
